### ISSUE TITLE
zoom buttons and date picker is not working in availability chart TSI

### ISSUE THREAD

**Issue by saisrinivas0695** [microsoft/tsiclient#293] opened 2020-12-01 04:15 UTC
Hi ,
we are using TSI charts to show our azure time series insights data . while developing we are facing a lot of issues in the availability line chart . zoom in and zoom out features are not working . In the date picker the dates were not selectable and maximum amount of data we can get is last three months but we need to enable the date picker to select beyond  3 months
please fix this issue ASAP.

**Comment by darsney** [comment] 2020-12-01 20:20
Please leave a reproduction of this issue in a codepen (or similar minimal reproduction in an interactive web environment).  This is unlikely to be an issue with the SDK since we regularly use this component in production, it is probably due to the way you are consuming it.  If you can show me what you are doing, I can help you consume the component in a way that works for your scenario

**Comment by darsney** [comment] 2020-12-08 01:53
Closing as we discussed the issue in a separate conversation

**Closed by darsney** 2020-12-08 01:53 UTC
